### ISSUE TITLE
missing icons on Pornbay

### ISSUE THREAD

**Issue by Djangox** [colligere/collapse_duplicates#1]
Hi there, just found your script about an hour ago. I was using "whatcd gazelle collapse duplicates ver 17" (since earlier today-grin). When I use your version 25.1, I do not get the "freeleech","checked by staff", etc icons.

I have tried both in Firefox & Chrome using Tampermonkey (4.9.4951[FF] & 4.8.41[C]). Both with "use emp style icons" & "vertical" checked & unchecked.

**Comment by colligere** [comment]
Apparently I didn't get a notification for your issue, so sorry for the (very) late reply.

I don't have a pornbay account, so I can't test any changes there. For now, there's not a lot I can do I'm afraid...

**Comment by colligere** [comment]
Should be solved now.
